### ISSUE TITLE
View - Estoque

### ISSUE THREAD

**Issue by JVTemponi** [ICEI-PUC-Minas-PMGES-TI/pmg-es-2024-1-ti3-9545100-drink-up#27]

**Comment by YoshuJumpMaster** [comment]
detalhamento da story: 

ajustar cor, ajustar estilização.

Nunito Sans - A FONTE. UTILIZAR EM TITULOS COMO BLACK ITALIC

Para textos pequenos utilizar o "Medium 500" e para titulos "Weight 1000"

**Comment by YoshuJumpMaster** [comment]
NOVA TELA

**Comment by YoshuJumpMaster** [comment]
<img width="868" alt="image" src="https://github.com/ICEI-PUC-Minas-PMGES-TI/pmg-es-2024-1-ti3-9545100-drink-up/assets/86268101/2c4cc9b9-f1fc-4226-a283-08f7c0407a9b">
