### ISSUE TITLE
Ajustar fonte texto da aplicação

### ISSUE THREAD

**Issue by JVTemponi** [ICEI-PUC-Minas-PMGES-TI/pmg-es-2024-1-ti3-9545100-drink-up#31]

**Comment by YoshuJumpMaster** [comment]
detalhamento da story: 

ajustar cor, ajustar estilização.

Nunito Sans - A FONTE. UTILIZAR EM TITULOS COMO BLACK ITALIC

Para textos pequenos utilizar o "Medium 500" e para titulos "Weight 1000"

**Comment by YoshuJumpMaster** [comment]
ajustar texto em todas páginas da aplicação.

**Comment by YoshuJumpMaster** [comment]
alterações em todas páginas finalizada
