### ISSUE TITLE
Refatoração Estoque -  Conexão com o front-back

### ISSUE THREAD

**Issue by sophiaamr** [ICEI-PUC-Minas-PMGES-TI/pmg-es-2024-1-ti3-9545100-drink-up#63]

**Comment by YoshuJumpMaster** [comment]
prova de funcionamento da página:   


<img width="1440" alt="image" src="https://github.com/ICEI-PUC-Minas-PMGES-TI/pmg-es-2024-1-ti3-9545100-drink-up/assets/86268101/2bd83c3c-5184-42ad-adc9-7592bbfd93c9">
